version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: casapiu-postgres
    environment:
      POSTGRES_USER: casapiu
      POSTGRES_PASSWORD: casapiu_dev_password
      POSTGRES_DB: casapiu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U casapiu"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - casapiu-network

  # Redis (per APScheduler job store)
  redis:
    image: redis:7-alpine
    container_name: casapiu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - casapiu-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: casapiu-backend
    environment:
      - DATABASE_URL=postgresql://casapiu:casapiu_dev_password@postgres:5432/casapiu
      - REDIS_URL=redis://redis:6379/0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - FIREBASE_KEY_PATH=/app/firebase-key.json
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
      - ./backend/firebase-key.json:/app/firebase-key.json:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - casapiu-network

  # PgAdmin (opzionale - per gestione database)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: casapiu-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@casapiu.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - casapiu-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  casapiu-network:
    driver: bridge
